import "../globals.css";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  fallback: ["system-ui", "arial"],
});

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (session) {
    redirect("/");
  } else {
    return (
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    );
  }
}
