import "../globals.css";
import { Poppins } from "next/font/google";
import AdminSidebar from "@/components/Sidebar/AdminSidebar";
import AuthProvider from "@/context/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  fallback: ["system-ui", "arial"],
});

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} flex gap-x-3 bg-light dark:bg-dark dark:text-white`}
      >
        <AuthProvider>
          <AdminSidebar />
          <main className="m-5 w-full">{children}</main>
          <div id="modal-root" />
        </AuthProvider>
      </body>
    </html>
  );
}
