import "./globals.css";
import { Poppins } from "next/font/google";
import Nav from "@/components/Nav";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Nav />
        <Header />
        <div className="container mx-auto md:px-10 px-5">{children}</div>
      </body>
    </html>
  );
}
