import "../globals.css";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import AuthProvider from "@/context/AuthProvider";
import { Poppins } from "next/font/google";
import Nav from "@/components/Nav";
import Header from "@/components/Header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  fallback: ["system-ui", "arial"],
});

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-light dark:bg-dark dark:text-white`}
      >
        <AuthProvider>
          <Nav session={session} />
          <Header />
          <div className="container mx-auto md:px-10 px-5">{children}</div>
          <div id="modal-root" />
        </AuthProvider>
      </body>
    </html>
  );
}
